/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package classes;

/**
 *
 * @author Rafael R. Sanches
 */
public class TelaSuperCalculadora extends javax.swing.JFrame {

    /**
     * Creates new form TelaSuperCalculadora
     */
    public TelaSuperCalculadora() { // CONSTRUTOR
        initComponents();
        pnRes.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        spnValor = new javax.swing.JSpinner();
        btnCalc = new javax.swing.JButton();
        pnRes = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblRes1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblRes2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblRes3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblRes4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblRes5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Informe um valor");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        spnValor.setModel(new javax.swing.SpinnerNumberModel(1, -50, 50, 1));

        btnCalc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/calculadoraIcon.png"))); // NOI18N
        btnCalc.setText("Calcular");
        btnCalc.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        jLabel2.setText("Resto da divisão por 2");

        lblRes1.setText("0");

        jLabel4.setText("Elevado ao cubo");

        lblRes2.setBackground(new java.awt.Color(102, 255, 102));
        lblRes2.setText("0");

        jLabel6.setText("Raiz quadrada");

        lblRes3.setBackground(new java.awt.Color(102, 255, 102));
        lblRes3.setText("0");

        jLabel8.setText("Raiz cúbica");

        lblRes4.setBackground(new java.awt.Color(102, 255, 102));
        lblRes4.setText("0");

        jLabel10.setText("Valor absoluto");

        lblRes5.setBackground(new java.awt.Color(102, 255, 102));
        lblRes5.setText("0");

        javax.swing.GroupLayout pnResLayout = new javax.swing.GroupLayout(pnRes);
        pnRes.setLayout(pnResLayout);
        pnResLayout.setHorizontalGroup(
            pnResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnResLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRes1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRes2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRes3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRes4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRes5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(14, 14, 14))
        );
        pnResLayout.setVerticalGroup(
            pnResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnResLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRes1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(pnResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRes2)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(pnResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRes3)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(pnResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRes4)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(pnResLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRes5)
                    .addComponent(jLabel10))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("Super Calculadora");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(spnValor, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCalc)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spnValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalc)
                .addGap(18, 18, 18)
                .addComponent(pnRes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed
        // TODO add your handling code here:
        int valor = (int) spnValor.getValue();
        
        lblRes1.setText(Integer.toString((int) (valor % 2)));
        lblRes2.setText(Float.toString((float) Math.pow(valor, 3)));
        lblRes3.setText(String.format("%.2f", (float) Math.sqrt(valor)));
        lblRes4.setText(String.format("%.2f", (float) Math.cbrt(valor)));
        lblRes5.setText(Float.toString(Math.abs(valor)));
        
        pnRes.setVisible(true);
    }//GEN-LAST:event_btnCalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaSuperCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaSuperCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaSuperCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaSuperCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaSuperCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblRes1;
    private javax.swing.JLabel lblRes2;
    private javax.swing.JLabel lblRes3;
    private javax.swing.JLabel lblRes4;
    private javax.swing.JLabel lblRes5;
    private javax.swing.JPanel pnRes;
    private javax.swing.JSpinner spnValor;
    // End of variables declaration//GEN-END:variables
}
